
jhon_queary_1 = {u'current_page': u'3',
                 u'page_count': 11,
                 u'data': [{u'isbn13': u'9781594512735',
                            u'marc_enc_level': u'~',
                            u'subject_ids': [u'nonfiction_social_sciences'],
                            u'publisher_name': u'Paradigm Publishers',
                            u'awards_text': u'',
                            u'title': u'The Depth of Shallow Culture: The High Art of Shoes, Movies, Novels, Monsters, and Toys',
                            u'title_long': u'The Depth of Shallow Culture: The High Art of Shoes, Movies, Novels, Monsters, and Toys (Studies in Comparative Social Science)',
                            u'physical_description_text': u'6.2"x8.7"x0.6"; 0.7 lb; 144 pages',
                            u'publisher_id': u'paradigm_publishers',
                            u'title_latin': u'The Depth of Shallow Culture: The High Art of Shoes, Movies, Novels, Monsters, and Toys',
                            u'publisher_text': u'Paradigm Publishers',
                            u'isbn10': u'1594512736',
                            u'language': u'',
                            u'lcc_number': u'',
                            u'notes': u'',
                            u'edition_info': u'Hardcover; 2006-08',
                            u'summary': u'Come take a closer look at ordinary footwear, like sneakers, or children\ufffds toys and Saturday cartoon TV shows, or make a comparison between Don Quixote and John Rambo of the Sylvester Stallone movies. Although some regard popular culture as "shallow," this book reveals that it is more often complex, deep, meaningful\ufffdand subject to the style changes we associate with high art. Bergesen shows how complex philosophical ideas of reincarnation are embedded in Transformer toys; how sneakers have gone through a life cycle of style types; why the decline of empires like Spain and the United States led to fictional characters like Don Quixote and Rambo, and why monsters from Japan look different than those from the United States.',
                            u'dewey_decimal': u'306.0973',
                            u'book_id': u'the_depth_of_shallow_culture_the_high_art_of_shoes_movie_a01',
                            u'dewey_normal': u'306.0973',
                            u'urls_text': u'',
                            u'author_data': [{u'id': u'bergesen_albert',
                                              u'name': u'Bergesen, Albert'}]},
                           {u'isbn13': u'9781594512742',
                            u'marc_enc_level': u'~',
                            u'subject_ids': [], u'publisher_name': u'Paradigm Publishers',
                            u'awards_text': u'',
                            u'title': u'The Depth of Shallow Culture: The High Art of Shoes, Movies, Novels, Monsters, and Toys', u'title_long': u'The Depth of Shallow Culture: The High Art of Shoes, Movies, Novels, Monsters, and Toys (Studies in Comparative Social Science)', u'physical_description_text': u'144 pages', u'publisher_id': u'paradigm_publishers', u'title_latin': u'The Depth of Shallow Culture: The High Art of Shoes, Movies, Novels, Monsters, and Toys',
                            u'publisher_text': u'Paradigm Publishers',
                            u'isbn10': u'1594512744', u'language': u'',
                            u'lcc_number': u'',
                            u'notes': u'',
                            u'edition_info': u'Paperback; 2007-01',
                            u'summary': u'Come take a closer look at ordinary footwear, like sneakers, or childrens toys and Saturday cartoon TV shows, or make a comparison between Don Quixote and John Rambo of the Sylvester Stallone movie. Although some regard popular culture as shallow, this book reveals that it is more often complex, deep, meaningfuland subject to the style changes we associate with high art. Bergesen shows how complex philosophical ideas of reincarnation are embedded in Transformer toys; how sneakers have gone through a life cycle of style types; why the decline of empires like Spain and the United States led to fictional characters like Don Quixote and Rambo; and why monsters from Japan look different than those from the United States.',
                            u'dewey_decimal': u'306',
                            u'book_id': u'the_depth_of_shallow_culture_the_high_art_of_shoes_movies_no',
                            u'dewey_normal': u'306',
                            u'urls_text': u'',
                            u'author_data': [{u'name': u'Bergesen, Albert',
                                              u'id': u'bergesen_albert'}]},
                           {u'marc_enc_level': u'~',
                            u'subject_ids': [u'science_fiction_fantasy_authors_a_z_r_reed_robert',
                                             u'science_fiction_fantasy_fantasy_anthologies',
                                             u'science_fiction_fantasy_science_fiction_anthologies',
                                             u'science_fiction_fantasy_science_fiction_short_stories',
                                             u'science_fiction_fantasy_general'],
                            u'publisher_name': u'Wyrm Publishing',
                            u'awards_text': u'',
                            u'title': u'Realms 2: The Second Year of Clarkesworld Magazine SC',
                            u'title_long': u'',
                            u'physical_description_text': u'5.5"x8.4"x0.6"; 0.7 lb; 256 pages',
                            u'publisher_id': u'wyrm_publishing',
                            u'title_latin': u'Realms 2: The Second Year of Clarkesworld Magazine SC',
                            u'isbn10': u'1890464104',
                            u'publisher_text': u'Wyrm Publishing',
                            u'language': u'',
                            u'isbn13': u'9781890464103',
                            u'lcc_number': u'',
                            u'notes': u'',
                            u'edition_info': u'Paperback; 2010-03-30',
                            u'summary': u'Selected from the Hugo award-nominated Clarkesworld Magazine, Realms collects the work of twenty-five visionary writers of short fiction, including such World Fantasy, Philip K. Dick, Tiptree, Hugo, and Campbell Award winners and finalists as Jeffrey Ford, Mary Robinette Kowal, Jay Lake, Cat Rambo, Tim Pratt, Robert Reed, Mike Resnick, and Catherynne M. Valente - and amazing stories from up-and-comers like Karen Heuler, Paul Jessup, Yoon Ha Lee, Margaret Ronald, and many more!',
                            u'dewey_decimal': u'813',
                            u'book_id': u'realms_2_the_second_year_of_clarkesworld_magazine_sc',
                            u'dewey_normal': u'813',
                            u'urls_text': u'',
                            u'author_data': [{u'name': u'Jeffery Ford',
                                              u'id': u'jeffery_ford'},
                                             {u'name': u'Jay Lake',
                                              u'id': u'jay_lake'},
                                             {u'name': u'Cat Rambo',
                                              u'id': u'cat_rambo'},
                                             {u'name': u'Tim Pratt',
                                              u'id': u'tim_pratt'},
                                             {u'name': u'Reed, Robert Rentoul',
                                              u'id': u'reed_robert_rentoul'},
                                             {u'id': u'catherynne_m_valente',
                                              u'name': u'Catherynne M. Valente'}]},
                           {u'marc_enc_level': u'~',
                            u'subject_ids': [u'literature_fiction',
                                             u'science_fiction_fantasy_science_fiction_anthologies',
                                             u'science_fiction_fantasy_science_fiction_short_stories'],
                            u'publisher_name': u'Running Press',
                            u'awards_text': u'',
                            u'title': u'The Mammoth Book of Steampunk',
                            u'title_long': u'',
                            u'physical_description_text': u'7.6"x9.7"x1.3"; 0.8 lb; 512 pages',
                            u'publisher_id': u'running_press',
                            u'title_latin': u'The Mammoth Book of Steampunk',
                            u'isbn10': u'0762444681',
                            u'publisher_text': u'Running Press',
                            u'isbn13': u'9780762444687',
                            u'language': u'',
                            u'lcc_number': u'',
                            u'notes': u'',
                            u'edition_info': u'Paperback; 2012-06-05',
                            u'summary': u'An anthology focusing on newer elements of steampunk, one which deconstructs the staples of the genre and expands on them, rather than simply repeating them, with a greater spread both in terms of location and character. This is steampunk with a modern, post-colonial sensibility. Contributors include: Jeff VanderMeer, Caitlin Kiernan Paul Di Filippo, Mary Robinette Kowal, Jay Lake, Cherie Priest, Cat Rambo, Ekaterina Sedia, Catherynne M. Valente, Genevieve Valentine and many more',
                            u'dewey_decimal': u'',
                            u'book_id': u'the_mammoth_book_of_steampunk_a01',
                            u'dewey_normal': u'0',
                            u'urls_text': u'',
                            u'author_data': [{u'id': u'sean_wallace',
                                              u'name': u'Sean Wallace'}]},
                           {u'marc_enc_level': u'~',
                            u'subject_ids': [],
                            u'publisher_name': u'Wallflower Press',
                            u'awards_text': u'',
                            u'title': u'War Cinema: Hollywood on the Front Line',
                            u'title_long': u'War Cinema: Hollywood on the Front Line (Short Cuts)',
                            u'physical_description_text': u'144 pages', u'publisher_id': u'wallflower_press',
                            u'language': u'',
                            u'title_latin': u'War Cinema: Hollywood on the Front Line',
                            u'publisher_text': u'Wallflower Press', u'isbn10': u'1904764541',
                            u'isbn13': u'9781904764540',
                            u'lcc_number': u'',
                            u'notes': u'',
                            u'edition_info': u'Paperback; 2005-12-15',
                            u'summary': u'An introduction to and overview of the Hollywood war movie, a linchpin in American cultural imagination. The book considers the history of this genre, one of continuing significance, from All Quiet on the Western Front (1930) to We Were Soldiers (2002). Guy Westwell focuses in particular on representations of the Vietnam War ( Apocalypse Now [1979], Rambo [1985] and Platoon [1986]) and the more recent return to and reexamination of the Second World War ( Saving Private Ryan [1998]).',
                            u'dewey_decimal': u'791',
                            u'book_id': u'war_cinema_hollywood_on_the_front_line',
                            u'dewey_normal': u'791',
                            u'urls_text': u'',
                            u'author_data': [{u'name': u'Guy Westwell', u'id': u'guy_westwell'}]},
                           {u'isbn13': u'9780552138321',
                            u'marc_enc_level': u'~',
                            u'subject_ids': [],
                            u'publisher_name': u'Transworld Publishers',
                            u'awards_text': u'',
                            u'title': u'They Came and Ate Us',
                            u'title_long': u'',
                            u'physical_description_text': u'336 pages',
                            u'publisher_id': u'transworld_publishers',
                            u'title_latin': u'They Came and Ate Us',
                            u'publisher_text': u'Transworld Publishers',
                            u'isbn10': u'0552138320',
                            u'language': u'',
                            u'lcc_number': u'',
                            u'notes': u'',
                            u'edition_info': u'Mass Market Paperback; 1992-04-23',
                            u'summary': u'QUIVER AT! horrible demonic stuff oozing out of computer screens! SHOCK HORROR! Elvis Presley pulling his face off GASP AT! a talking brussels sprout! SEE! Cannibals on the rampage! HEAR! Fido the Dog do Frankie Howerd impressions! SEE! Rex Mundi, Rambo Bloodaxe, Deathblade Eric, Hugo Rune and a cast of millions caught up in Events Beyond Their Control! THRILL TO! all the loose ends from Armageddon The Musical magically tied up! WATCH! A comic genius doing the business! SEE?',
                            u'dewey_decimal': u'',
                            u'book_id': u'they_came_and_ate_us_a01',
                            u'dewey_normal': u'0',
                            u'urls_text': u'',
                            u'author_data': [{u'name': u'Rankin, Robert',
                                              u'id': u'rankin_robert'}]},
                           {u'isbn13': u'9780768450101',
                            u'marc_enc_level': u'~',
                            u'subject_ids': [],
                            u'publisher_name': u'Fresh Bread',
                            u'awards_text': u'',
                            u'title': u'Follow the Yellow Brick Road',
                            u'title_long': u'',
                            u'physical_description_text': u'272 pages',
                            u'publisher_id': u'fresh_bread',
                            u'title_latin': u'Follow the Yellow Brick Road',
                            u'publisher_text': u'Fresh Bread',
                            u'isbn10': u'0768450101',
                            u'language': u'',
                            u'lcc_number': u'',
                            u'notes': u'',
                            u'edition_info': u'Paperback; 2001-12-01',
                            u'summary': u"Reba Rambo-McGuire has dared open a few top-secret files from her private life to help other who need an awesome proof of God's love and forgiveness, His redemption and restoration. Wherever you are on your pilgrimage from Kansas to Oz and back, you may have been caught up in a whirlwind or two. You may feel as though life has come crashing down. You may not know where on earth you are, but Heaven woos, summoning you to a higher realm of destiny. God has revealed golden stepping stones-simple truths and answers, life lessons and secrets-to guide you to King Jesus and the home He has for you! From a poor, lonely childhood in the coal mining regions of southwestern Kentucky to the pinnacle of contemporary Christian music, Reba Rambo-McGuire grew up singing gospel music in the long shadow of her famous parents, Buck and Dottie Rambo. But her life has been anything but idyllic, with her first marriage ending in a life-shattering divorce followed by the grim revelation of a dark family secret, and then her turbulent marriage to Dony McGuire, a serious substance abuser. Join Reba for what promises to be a momentous journey...and grab a handful of tissues. You'll soon discover the power of God to transform the lives of those who pursue Him.", u'dewey_decimal': u'', u'book_id': u'follow_the_yellow_brick_road_a01', u'dewey_normal': u'0', u'urls_text': u'', u'author_data': [{u'id': u'reba_rambo_mcguire', u'name': u'Reba Rambo-McGuire'}]}, {u'marc_enc_level': u'~', u'subject_ids': [u'literature_fiction_contemporary', u'literature_fiction_general_general', u'mystery_thrillers_thrillers_general'], u'publisher_name': u'Infinity Publishing', u'awards_text': u'', u'title': u'al-Qaeda Strikes Again', u'title_long': u'', u'physical_description_text': u'5.4"x8.3"x0.6"; 0.3 lb; 345 pages', u'publisher_id': u'infinity_publishing', u'language': u'', u'title_latin': u'al-Qaeda Strikes Again', u'publisher_text': u'Infinity Publishing', u'isbn10': u'0741449102', u'isbn13': u'9780741449108', u'lcc_number': u'', u'notes': u'', u'edition_info': u'Paperback; 2008-07', u'summary': u'The inexplicable suicide of a female passenger at JFK International Airport and a secret list discovered by authorities in Pakistan set the stage for a diabolical and deadly al-Qaeda plot involving simultaneous and catastrophic acts of terrorism across the United States. In a race against time, the only question is whether Terrorism Task Force Leader, Wayne Kirby, and his Rambo-like girlfriend, Rennie Jordon, will live long enough to unravel the details, find the terrorists and put a stop to their deadly jihad.', u'dewey_decimal': u'813', u'book_id': u'al_qaeda_strikes_again', u'dewey_normal': u'813', u'urls_text': u'', u'author_data': [{u'id': u'bill_binkley', u'name': u'Bill Binkley'}]}, {u'marc_enc_level': u'~', u'subject_ids': [u'science_fiction_fantasy_media_star_trek_general'], u'publisher_name': u'Books LLC', u'awards_text': u'', u'title': u'Films Directed by Actors: Rocky Iv, Star Trek Iv: the Voyage Home, That Thing You Do!, on Deadly Ground, Star Trek V', u'title_long': u'Films Directed by Actors: Rocky Iv, Star Trek Iv: the Voyage Home, That Thing You Do!, on Deadly Ground, Star Trek V: the Final Frontier', u'physical_description_text': u'6.0"x9.0"x2.1"; 3.0 lb; 950 pages', u'publisher_id': u'books_llc', u'title_latin': u'Films Directed by Actors: Rocky Iv, Star Trek Iv: the Voyage Home, That Thing You Do!, on Deadly Ground, Star Trek V', u'isbn10': u'1156470706', u'publisher_text': u'Books LLC', u'isbn13': u'9781156470701', u'language': u'', u'lcc_number': u'', u'notes': u'', u'edition_info': u'Paperback; 2010-05-20', u'summary': u"Purchase includes free access to book updates online and a free trial membership in the publisher's book club where you can select from more than a million books without charge. Chapters: Rocky Iv, Star Trek Iv: the Voyage Home, That Thing You Do!, on Deadly Ground, Star Trek V: the Final Frontier, the Night of the Hunter, P.s. Your Cat Is Dead, Rocky Iii, the Devil and Daniel Webster, Rocky Ii, Pollock, Kotch, Star Trek Iii: the Search for Spock, Kung Fu Hustle, Taare Zameen Par, Rocky Balboa, Game of Death, Shaolin Soccer, Rambo, Goodbye, Farewell and Amen, Slipstream, Garden State, Robot Chicken: Star Wars, the Life of Larry and Larry", u'dewey_decimal': u'', u'book_id': u'films_directed_by_actors_rocky_iv_star_trek_iv_the_voyage_ho', u'dewey_normal': u'0', u'urls_text': u'', u'author_data': [{u'name': u'Books LLC', u'id': u'books_llc'}]}, {u'isbn13': u'9780664235031', u'marc_enc_level': u'~', u'subject_ids': [u'religion_spirituality_christianity_theology'], u'publisher_name': u'Westminster John Knox Press', u'awards_text': u'', u'title': u'Spirit and Trauma', u'title_long': u'Spirit and Trauma: A Theology of Remaining', u'physical_description_text': u'6.0"x8.9"x0.5"; 0.8 lb; 176 pages', u'publisher_id': u'westminster_john_knox_press', u'title_latin': u'Spirit and Trauma', u'publisher_text': u'Westminster John Knox Press', u'isbn10': u'0664235034', u'language': u'', u'lcc_number': u'', u'notes': u'', u'edition_info': u'Paperback; 2010-09-02', u'summary': u'Rambo draws on contemporary studies in trauma to rethink a central claim of the Christian faith: that new life arises from death. Reexamining the narrative of the death and resurrection of Jesus from the middle day-liturgically named as Holy Saturday-she seeks a theology that addresses the experience of living in the aftermath of trauma. Through a reinterpretation of "remaining" in the Johannine Gospel, she proposes a new theology of the Spirit that challenges traditional conceptions of redemption. Offered, in its place, is a vision of the Spirit\'s witness from within the depths of human suffering to the persistence of divine love.', u'dewey_decimal': u'248.8625', u'book_id': u'spirit_and_trauma', u'dewey_normal': u'248.8625', u'urls_text': u'', u'author_data': [{u'id': u'shelly_rambo', u'name': u'Shelly Rambo'}, {u'id': u'keller_catherine', u'name': u'Keller, Catherine'}]}], u'index_searched': u'book_summary', u'result_count': 103}

clean_code_quert_01 = {u'index_searched': u'book_id', u'data': [{u'marc_enc_level': u'', u'subject_ids': [u'computers_internet_programming_languages_tools', u'computers_internet_programming_software_design_testing_engin', u'computers_internet_computer_science_software_engineering', u'agile_software_development', u'computer_software_reliability'], u'publisher_name': u'Prentice Hall', u'awards_text': u'', u'title': u'Clean code', u'title_long': u'Clean code: a handbook of agile software craftsmanship', u'physical_description_text': u'431p.', u'publisher_id': u'prentice_hall', u'title_latin': u'Clean code', u'isbn10': u'0132350882', u'publisher_text': u'Indianapolis, Ind. : Prentice Hall ; c2009.', u'language': u'eng', u'isbn13': u'9780132350884', u'lcc_number': u'QA76.76', u'notes': u'', u'edition_info': u'(pbk.)', u'summary': u'', u'dewey_decimal': u'005.1', u'book_id': u'clean_code_a_handbook_of_agile_software_craftsmanship', u'dewey_normal': u'5.1', u'urls_text': u'', u'author_data': [{u'name': u'Martin, Robert W. T.', u'id': u'martin_robert_w_t'}, {u'name': u'Michael Feathers', u'id': u'michael_feathers'}]}]}